env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
overrides: []
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - react-hooks
settings:
  import/resolver:
    - node
    - webpack
rules: 
  no-console: ['error', { allow: ['warn', 'error'] }]
  import/extensions: 'off'
  react/function-component-definition: [2, { "namedComponents": "arrow-function" }]
  react/no-unstable-nested-components: "off"
  react/prop-types: 'off'
  functional/no-conditional-statement: 'off'
  functional/no-expression-statement: 'off'
  functional/immutable-data: 'off'
  functional/functional-parameters: 'off'
  functional/no-try-statement: 'off'
  functional/no-throw-statement: 'off'
  jsx-a11y/label-has-associated-control: 'off'
